// src/app/layout.js

export const metadata = {
  title: "Saynt AI",
  description: "Generated by create next app",
  verification: {
    google: "MmlJkMyc3XcgPBM94aWb0eP_wFGfgkgaMi6KuMNUzp4",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

