import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import { Poppins } from "next/font/google";
import Header from "./components/Header";
import { Bricolage_Grotesque } from "next/font/google";
import { Saira } from "next/font/google";
import Footer from './components/Footer';
import 'swiper/css'
import '../../../public/sass/base/base.scss';
import '../../../public/sass/base/helper.scss';
import '../../../public/sass/base/reset.scss';
import Scroll_star from './components/scroll_star';
import { ToastContainer } from 'react-toastify';

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    preload: true,
    display: "swap"
});

const saira = Saira({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    preload: true,
    variable: '--font-bricologe',
    display: "swap"
});

const bricologe = Bricolage_Grotesque({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800"],
    preload: true,
    variable: '--font-bricologe',
    display: "swap"
});

export const metadata = {
    title: "Saynt AI",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang="en">
        <body id='pb_scroll' className={`${poppins.className} ${bricologe.variable} ${saira.variable}`}>
            <ToastContainer />
            <Header />
            <div className="section" id='section'>
                {children}
            </div>
            <Scroll_star />
            <Footer />
        </body>
    </html>
    );
}
